---
engines:
  phpcs:
    enabled: true
    php_version: 7.3
    exclude_paths:
      - 'bin/**'
      - 'config/**'
      - 'var/**'
      - 'var/SymfonyRequirements.php'
      - 'public/index.php'
      - 'public/bundles/apiplatform/**'
      - 'src/kernel.php'
      - 'tests'
  coverage:
    enabled: true
  exclude_paths:
    - 'bin/**'
    - 'config/**'
    - 'var/**'
    - 'var/SymfonyRequirements.php'
    - 'public/index.php'
    - 'public/bundles/apiplatform/**'
    - 'src/kernel.php'
    - 'tests'