version: "2"
exclude_patterns:
  - 'bin/**'
  - 'config/**'
  - 'var/**'
  - 'var/SymfonyRequirements.php'
  - 'public/index.php'
  - 'public/bundles/apiplatform/**'
  - 'src/kernel.php'
  - 'tests/**'
  - '.phan/**'

plugins:
  phpcodesniffer:
    enabled: true
    standard: "PSR1,PSR2"
  phpmd:
    enabled: true
  phan:
    enabled: true
    config:
      file_extensions: "php"
  sonar-php:
    enabled: true
    config:
      tests_patterns:
        - tests/**