language: php
os: linux
dist: trusty

cache: false

php:
  - '7.2'
  - '7.3'

# In case of timeouts and build failures you may want to prepend 'travis_retry' to the following commands:
before_script:
  - composer install

script:
  - php bin/phpunit
