env:
  global:
    - CC_TEST_REPORTER_ID=ff14f7183876ba0509b623f14150241093cd8b56bc7504f99d847b0d769e5bd8
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)

language: php
os: linux
sudo: required
dist: trusty

cache: false

php:
  - '7.3'
node_js:
      - 12

before_install:
  - npm i -g npm@6

# In case of timeouts and build failures you may want to prepend 'travis_retry' to the following commands:
before_script:
#  - sudo apt-get update -y && sudo apt-get upgrade -y
#  - sudo apt-get install python-software-properties
#  - sudo rm -rf ~/.nvm - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash –
#  - sudo apt-get install -y nodejs
#  - sudo ln -s /usr/bin/nodejs /usr/local/bin/node
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get -y update
  - sudo apt install yarn -y
  - composer install
  - yarn install
  - yarn encore dev
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - php bin/phpunit --coverage-text --coverage-clover var/log/clover.xml
#  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build  -t clover --exit-code $TRAVIS_TEST_RESULT; fi

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
